# Generated by Django 3.2.7 on 2021-09-13 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('tags', models.CharField(blank=True, help_text='Separated by commas', max_length=255, null=True, verbose_name='Tags')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='Hint')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('creator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Creator')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Task type',
                'verbose_name_plural': 'Task types',
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tasktype', verbose_name='Task type'),
        ),
        migrations.CreateModel(
            name='SolvedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved', to='tasks.task', verbose_name='Task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved', to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Solved task',
                'verbose_name_plural': 'Solved tasks',
            },
        ),
        migrations.CreateModel(
            name='FlagStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('flag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Flag')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Sent flag',
                'verbose_name_plural': 'Sent flags',
            },
        ),
    ]
