# Generated by Django 3.1.3 on 2020-11-29 14:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20201129_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('WEB', 'WEB'), ('REVERSE', 'REVERSE'), ('STEGO', 'STEGO'), ('CRYPTO', 'CRYPTO'), ('ADMIN', 'ADMIN'), ('JOY', 'JOY'), ('FORENSIC', 'FORENSIC'), ('PPC', 'PPC')], max_length=255, verbose_name='Тип')),
                ('video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео')),
                ('flag', models.CharField(max_length=255, verbose_name='Флаг')),
                ('creator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='SolvedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved', to='tasks.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved', to='teams.team')),
            ],
        ),
    ]
