# Generated by Django 3.1.3 on 2020-12-01 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AddField(
            model_name='solvedtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='hint',
            field=models.TextField(blank=True, null=True, verbose_name='Hint'),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Кол-во баллов'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
    ]
