version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  dbdata: {}

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: ctf_nginx
    networks:
      - default
      - ctf
    ports:
      - "9099:80"
    volumes:
      - .:/app
      - ./compose/nginx:/etc/nginx/conf.d
    depends_on:
      - django

  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: ctf_django
    networks:
      - ctf
    depends_on:
      - psql
    env_file:
      - .env
    volumes:
      - .:/app

  psql:
    restart: unless-stopped
    image: postgres:latest
    container_name: ctf_postgres
    networks:
      - ctf
    env_file:
      - .env


networks:
  ctf:
    name: ctf_network
