#!/bin/bash

set -o errexit
set -o nounset


celery flower \
    --app=conf.celery \
    --broker="redis://${REDIS_HOST}:${REDIS_PORT}/${CELERY_BROKER_DB}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
