# Generated by Django 3.1.3 on 2020-11-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fourth_fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Участника'),
        ),
        migrations.AddField(
            model_name='team',
            name='second_fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Участника'),
        ),
        migrations.AddField(
            model_name='team',
            name='third_fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Участника'),
        ),
        migrations.CreateModel(
            name='FlagStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='teams.team')),
            ],
            options={
                'verbose_name': 'Сданный флаг',
                'verbose_name_plural': 'Сданные флаги',
            },
        ),
    ]
