# Generated by Django 3.2.7 on 2021-09-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('newbies', 'Newbies'), ('experienced', 'Experienced')], max_length=255, verbose_name='Command type'),
        ),
    ]
