# Generated by Django 3.2.7 on 2021-09-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Is Superuser'),
        ),
    ]
