# Generated by Django 3.2.7 on 2021-09-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20210914_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pc_count',
            field=models.IntegerField(default=0, verbose_name='PC Count'),
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
