# Generated by Django 3.2.7 on 2021-09-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  # type: ignore
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OmCTF.Sib', max_length=255, verbose_name='Competitions name')),
                ('is_started', models.BooleanField(default=False, verbose_name='Is Competition Started')),
                ('max_participants', models.IntegerField(default=4, verbose_name='Max Participants in Team')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
